item {
 id: 1
 name: 'Salat'
}
item {
 id: 2
 name: 'Vorspeise'
}
item {
 id: 3
 name: 'Hauptspeise'
}
item {
 id: 4
 name: 'Beilage'
}
item {
 id: 5
 name: 'Getränk'
}
item {
 id: 6
 name: 'Dessert'
}
